### PR TITLE
Some periods, colons and commas for your consideration

### PR DESCRIPTION
**Pull request by leereilly**
Minor changes for the `README`...

Cheers,
  Lee :beers:

### CODE REVIEW

**Comment by sshirokov** [comment]
Merged **without** caution. :metal:

**Comment by sshirokov** [comment]
Sorry for the early merge :(

**Comment by sshirokov** [comment]
That actually made it into the merge according to my local repo...

**Comment by sshirokov** [comment]
So, you're welcome for the ON TIME merge.

**Comment by leereilly** [comment]
There's nothing I hate more than a _slow_ merge :metal:

**Pull request merged**
