### PR TITLE
automatically redirect to STL for tinkercad links

### PR DESCRIPTION
**Pull request by ymendel**
poly:ramen:

Pull Request: master

### CODE REVIEW

**Comment by skalnik** [comment]
:revolving_hearts:

**Comment by ymendel** [comment]
I suggest you merge this and try it with your next print.

**Comment by skalnik** [comment]
Did you test locally?

**Comment by ymendel** [comment]
Pffft, no.

I mean, I know the method works. I just didn't do the full stack.

**Comment by ymendel** [comment]
``` ruby
>> d = Download.new('https://tinkercad.com/things/5jC2fnv5Rfi/polysoup.stl', 'bah')
=> #<Download:0x007fe5b5051958 @url="https://tinkercad.com/things/5jC2fnv5Rfi/polysoup.stl", @output_file="bah">
>> d.url
=> "https://tinkercad.com/things/5jC2fnv5Rfi/polysoup.stl"
>> d.thing_url
=> "https://tinkercad.com/things/5jC2fnv5Rfi/polysoup.stl"
>> d = Download.new('https://tinkercad.com/things/5jC2fnv5Rfi-sizzling-jaban/', 'bah')
=> #<Download:0x007fe5b500c560 @url="https://tinkercad.com/things/5jC2fnv5Rfi-sizzling-jaban/", @output_file="bah">
>> d.url
=> "https://tinkercad.com/things/5jC2fnv5Rfi-sizzling-jaban/"
>> d.thing_url
=> "https://tinkercad.com/things/5jC2fnv5Rfi/polysoup.stl"
```

**Comment by skalnik** [comment]
Sexy

**Pull request merged**
