### PR TITLE
Optimize this

### PR DESCRIPTION
**Pull request by sshirokov**
Stop doing Miracle Grue graph optimizations

Randomly turn the coarsens knobs.

cc/ @skalnik

### CODE REVIEW

**Comment by skalnik** [comment]
I like this.

**Comment by skalnik** [comment]
I am @skalnik and I approve this message :+1: :us:

**Comment by sshirokov** [comment]
As far as I can tell this made absolutely no difference.

**Comment by skalnik** [comment]
Fuck it. Lets use Cura.

**Pull request closed without merging**
