### PR TITLE
Kill all tmp/*.pids

### PR DESCRIPTION
**Pull request by skalnik**
Kill multiple pid files.

I guess here we should discuss keeping them in `tmp/` versus splitting them into `run/`. Any thoughts? I like keeping just the 1 directory for all the project stuff, but I can see splitting the pids into a separate directory not being a bad idea. Any thoughts @sshirokov, @thedaniel?

### CODE REVIEW

**Comment by sshirokov** [comment]
I don't like spreading the pids around at all.

**Comment by skalnik** [comment]
Seems that `slice.pid` and `print.pid` are both empty when written.

**Comment by skalnik** [comment]
This is stale as fuck. Do we still need it? /cc @sshirokov

**Comment by sshirokov** [comment]
We might as well just close it until we have a safe way to kill remotely.

**Pull request closed without merging**
